// Autogenerated from Pigeon (v10.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class CameraPath;

@interface CameraPath : NSObject
+ (instancetype)makeWithImagePath:(nullable NSString *)imagePath;
@property(nonatomic, copy, nullable) NSString * imagePath;
@end

/// The codec used by CameraPathApi.
NSObject<FlutterMessageCodec> *CameraPathApiGetCodec(void);

@protocol CameraPathApi
/// @return `nil` only when `error != nil`.
- (nullable CameraPath *)takeCameraImageWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void CameraPathApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CameraPathApi> *_Nullable api);

/// The codec used by ImagePathCallback.
NSObject<FlutterMessageCodec> *ImagePathCallbackGetCodec(void);

@interface ImagePathCallback : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onImagePathUpdatedImagePath:(nullable NSString *)imagePath completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
