// Autogenerated from Pigeon (v10.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "cameraAccess.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface CameraPath ()
+ (CameraPath *)fromList:(NSArray *)list;
+ (nullable CameraPath *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation CameraPath
+ (instancetype)makeWithImagePath:(nullable NSString *)imagePath {
  CameraPath* pigeonResult = [[CameraPath alloc] init];
  pigeonResult.imagePath = imagePath;
  return pigeonResult;
}
+ (CameraPath *)fromList:(NSArray *)list {
  CameraPath *pigeonResult = [[CameraPath alloc] init];
  pigeonResult.imagePath = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable CameraPath *)nullableFromList:(NSArray *)list {
  return (list) ? [CameraPath fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.imagePath ?: [NSNull null]),
  ];
}
@end

@interface CameraPathApiCodecReader : FlutterStandardReader
@end
@implementation CameraPathApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [CameraPath fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface CameraPathApiCodecWriter : FlutterStandardWriter
@end
@implementation CameraPathApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[CameraPath class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface CameraPathApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation CameraPathApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[CameraPathApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[CameraPathApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *CameraPathApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    CameraPathApiCodecReaderWriter *readerWriter = [[CameraPathApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void CameraPathApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CameraPathApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.pigeon_sample2.CameraPathApi.takeCameraImage"
        binaryMessenger:binaryMessenger
        codec:CameraPathApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(takeCameraImageWithError:)], @"CameraPathApi api (%@) doesn't respond to @selector(takeCameraImageWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        CameraPath *output = [api takeCameraImageWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
NSObject<FlutterMessageCodec> *ImagePathCallbackGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

@interface ImagePathCallback ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation ImagePathCallback

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onImagePathUpdatedImagePath:(nullable NSString *)arg_imagePath completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.pigeon_sample2.ImagePathCallback.onImagePathUpdated"
      binaryMessenger:self.binaryMessenger
      codec:ImagePathCallbackGetCodec()];
  [channel sendMessage:@[arg_imagePath ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
@end

